Updated docs. Fixes #2
- Clarified running standalone behat vs in conjunction with Selenium in a Docker Compose stack
- Removed references to fin (since this is maintained as standalone image)

diff --git a/example/run-behat b/example/run-behat
--- a/example/run-behat
+++ b/example/run-behat
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
+set -e  # Fail on errors
+
 # Run behat commands in a running behat container
-# Have to use `docker exec`, since `docker-compose run` won't work on Windows
-# Make sure this works directly or via Docksal Fin
-if (type fin >/dev/null 2>&1); then fin_cmd='fin'; fi
-$fin_cmd docker exec $($fin_cmd docker-compose ps -q behat) behat --colors --format=pretty --out=std --format=html --out=html_report "$@"
+# Have to use `docker exec`, since `docker-compose run` won't work on Windows (TODO: is this still true?)
+docker exec $(docker-compose ps -q behat) behat --colors --format=pretty --out=std --format=html --out=html_report "$@"
 
 echo "To view HTML report visit: http://<your-docker-host-ip>:8000/html_report"
